version: '3'

services:
  data-producer:
    build: ./data-producer
    image: data-producer-img:latest
    ports:
      - "8080:8080"
    restart: on-failure
    links:
      - rabbitmq
    networks:
      - data-pipeline-network
      
  data-consumer:
    build: ./data-consumer
    image: data-consumer-img:latest
    ports:
      - "8082:8082"
    restart: on-failure
    links:
      - rabbitmq
      - mongodb
    networks:
      - data-pipeline-network  
      
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - data-pipeline-network
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    volumes:
      - mongodb:/data/userdatadb
      - mongodb_config:/data/configuserdatadb
    ports:
        - 27017:27017
    networks:
      - data-pipeline-network
networks:
  data-pipeline-network:
    driver: bridge
volumes:
  mongodb:
  mongodb_config: